// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabFIS1CuUgkrd8AP8jqrdSEsub1zNCd4',
    appId: '1:677849260890:web:6ce00903554186ced50963',
    messagingSenderId: '677849260890',
    projectId: 'smart-dental-care-system-622e0',
    authDomain: 'smart-dental-care-system-622e0.firebaseapp.com',
    storageBucket: 'smart-dental-care-system-622e0.firebasestorage.app',
    measurementId: 'G-MCVL9TBVS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATIbA0ynPG1-PyXgy-MymsknRND-v9mRY',
    appId: '1:677849260890:android:2324ccff1821032bd50963',
    messagingSenderId: '677849260890',
    projectId: 'smart-dental-care-system-622e0',
    storageBucket: 'smart-dental-care-system-622e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxV2sWQZLLiYsQ27TCnJf2tj7u9bG5_Ms',
    appId: '1:677849260890:ios:66ef07c2f84324add50963',
    messagingSenderId: '677849260890',
    projectId: 'smart-dental-care-system-622e0',
    storageBucket: 'smart-dental-care-system-622e0.firebasestorage.app',
    iosBundleId: 'com.example.smartDentalCareSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxV2sWQZLLiYsQ27TCnJf2tj7u9bG5_Ms',
    appId: '1:677849260890:ios:66ef07c2f84324add50963',
    messagingSenderId: '677849260890',
    projectId: 'smart-dental-care-system-622e0',
    storageBucket: 'smart-dental-care-system-622e0.firebasestorage.app',
    iosBundleId: 'com.example.smartDentalCareSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBabFIS1CuUgkrd8AP8jqrdSEsub1zNCd4',
    appId: '1:677849260890:web:58d661148e9afd52d50963',
    messagingSenderId: '677849260890',
    projectId: 'smart-dental-care-system-622e0',
    authDomain: 'smart-dental-care-system-622e0.firebaseapp.com',
    storageBucket: 'smart-dental-care-system-622e0.firebasestorage.app',
    measurementId: 'G-GYC2CXP5TE',
  );
}
